"""
Jacobian correctness sweeps.

1. Every map's hand-written ``_jacobian`` is validated against central finite
   differences of ``_step`` at points on the attractor.  Discontinuous maps
   (``abs``, ``sign``, modulo wrapping) legitimately fail at measure-zero
   kinks, so each point votes and 75 % must pass; genuinely pathological
   classes can opt out via ``_jacobian_fd_check = False``.
2. Every ODE system that hand-defines ``_jacobian`` is cross-checked against
   the SymEngine-autogenerated Jacobian (``ContinuousSystem.jacobian``) at
   random states — any disagreement is a real bug in the hand-written matrix.
"""

from __future__ import annotations

import inspect

import numpy as np
import pytest

_N_POINTS = 8
_PASS_FRACTION = 0.75
_FD_H = 1e-6


def _on_attractor_points(sys, n: int) -> np.ndarray:
    """Iterate past the transient and return ``n`` orbit points."""
    traj = sys.iterate(steps=60 + n, max_retries=15)
    return traj.y[60:]


def _fd_jacobian(step, x: np.ndarray, params: tuple) -> np.ndarray:
    """Central finite-difference Jacobian of ``step`` at ``x``."""
    dim = x.shape[0]
    J = np.empty((dim, dim))
    for j in range(dim):
        h = _FD_H * max(1.0, abs(x[j]))
        xp, xm = x.copy(), x.copy()
        xp[j] += h
        xm[j] -= h
        fp = np.asarray(step(xp, *params), dtype=float).ravel()
        fm = np.asarray(step(xm, *params), dtype=float).ravel()
        J[:, j] = (fp - fm) / (2.0 * h)
    return J


def test_map_jacobian_matches_finite_differences(map_entry) -> None:
    cls = map_entry.cls
    if not getattr(cls, "_jacobian_fd_check", True):
        pytest.skip(f"{map_entry.name} opted out (_jacobian_fd_check = False)")

    sys = cls()
    params = sys.params.as_tuple()
    step, jac = type(sys)._step, type(sys)._jacobian

    points = _on_attractor_points(sys, _N_POINTS)
    votes = []
    for x in points:
        J_analytic = np.atleast_2d(np.asarray(jac(x.copy(), *params), dtype=float))
        J_fd = _fd_jacobian(step, x.copy(), params)
        if not (np.all(np.isfinite(J_analytic)) and np.all(np.isfinite(J_fd))):
            continue  # divergent/kink point — abstain
        votes.append(np.allclose(J_analytic, J_fd, rtol=1e-4, atol=1e-6))

    assert votes, f"{map_entry.name}: no finite Jacobian evaluations on the orbit"
    fraction = sum(votes) / len(votes)
    assert fraction >= _PASS_FRACTION, (
        f"{map_entry.name}._jacobian disagrees with finite differences at "
        f"{(1 - fraction) * 100:.0f}% of sampled orbit points — likely a wrong entry."
    )


# ---------------------------------------------------------------------------
# ODE: hand-written _jacobian vs SymEngine autogenerated jacobian()
# ---------------------------------------------------------------------------


def _call_handwritten_jacobian(cls, sys, y_sym, t_sym):
    """Call ``_jacobian`` coping with the historical signature variations."""
    fn = cls._jacobian
    params = list(inspect.signature(fn).parameters.values())[2:]  # after (Y, t)
    if any(p.kind == p.VAR_KEYWORD for p in params):
        kwargs = sys.params.as_dict()
    else:
        names = {p.name for p in params}
        kwargs = {k: v for k, v in sys.params.as_dict().items() if k in names}
    return list(fn(y_sym, t_sym, **kwargs))


def test_ode_handwritten_jacobian_matches_autogen(ode_entry, rng) -> None:
    import symengine
    from jitcode import t as t_sym
    from jitcode import y as y_sym

    cls = ode_entry.cls
    if "_jacobian" not in cls.__dict__:
        pytest.skip(f"{ode_entry.name} has no hand-written _jacobian")

    sys = cls()
    rows = _call_handwritten_jacobian(cls, sys, y_sym, t_sym)

    for _ in range(5):
        u = rng.uniform(-2.0, 2.0, size=sys.dim)
        subs = {y_sym(i): float(u[i]) for i in range(sys.dim)}
        subs[t_sym] = 0.0
        hand = np.array([[float(symengine.sympify(e).subs(subs)) for e in row] for row in rows])
        auto = sys.jacobian(u, t=0.0)
        np.testing.assert_allclose(
            hand,
            auto,
            rtol=1e-9,
            atol=1e-12,
            err_msg=(
                f"{ode_entry.name}: hand-written _jacobian disagrees with the "
                f"SymEngine-autogenerated Jacobian at u={u} — the hand-written "
                f"matrix has a wrong entry."
            ),
        )
