#!/usr/bin/env python3
"""Generate the golden tape fixtures consumed by ``tests/golden_fixtures.rs``.

This is the *Python* end of the Python↔Rust round-trip that guards the frozen
IR contract.  For each chosen system it:

1. lowers the symbolic right-hand side (and analytic Jacobian) to a tape with the
   v2 emitter (:func:`tsdynamics.engine.rustcore.compile_tape`) — exactly the
   integer arrays the engine ships across the FFI boundary;
2. evaluates the *symbolic* RHS and Jacobian at a few checkpoints via the
   system's own ``_rhs_numeric`` / ``jacobian`` (an engine-independent ground
   truth);
3. writes both to a ``fixtures/<system>.txt`` file.

The Rust test reads each fixture, rebuilds the tape via ``Tape::from_arrays`` and
evaluates it with the reference evaluator, asserting it reproduces the symbolic
checkpoints to ~1e-12.  ``tests/test_ir_contract.py`` re-runs this generator and
diffs the result against the committed files, so the emitter cannot silently
drift from the arrays Rust was validated against.

Regenerate after touching the emitter, the chosen systems, or their parameters::

    python crates/tsdyn-ir/tests/gen_fixtures.py
"""

from __future__ import annotations

import pathlib

import numpy as np

# The greedy opcode cover: these six systems together exercise every opcode the
# 118-ODE catalogue actually emits — TIME (Torus), ABS/SIGN/TANH (SanUm),
# SINH/COSH (YuWang2), EXP (SprottMore), POW/POWI/RECIP/SIN/COS (CircadianRhythm)
# — on top of Lorenz's polynomial core. Checkpoints are fixed, in-domain points;
# Torus is non-autonomous so it is probed at two times.
FIXTURE_SYSTEMS: dict[str, dict] = {
    "Lorenz": {"u": [[1.0, 1.0, 1.0], [2.0, -1.0, 0.5]], "t": [0.0, 0.0]},
    "CircadianRhythm": {"u": [[0.5, 0.6, 0.7, 0.8, 0.4]], "t": [0.0]},
    "SanUmSrisuchinwong": {"u": [[0.4, -0.7, 1.1], [-1.3, 0.9, -0.2]], "t": [0.0, 0.0]},
    "YuWang2": {"u": [[0.3, -0.5, 0.8], [1.2, 0.4, -0.9]], "t": [0.0, 0.0]},
    "SprottMore": {"u": [[0.2, -0.4, 0.6], [-0.8, 0.5, 0.1]], "t": [0.0, 0.0]},
    "Torus": {"u": [[0.5, -0.3, 0.9], [1.1, 0.7, -0.4]], "t": [0.0, 0.7]},
}

_HEADER = (
    "# tsdyn-ir golden fixture — generated by gen_fixtures.py; do not hand-edit.\n"
    "# Regenerate with: python crates/tsdyn-ir/tests/gen_fixtures.py\n"
)


def _fmt_floats(xs) -> str:
    # repr() gives the shortest round-trippable decimal; Rust's f64 parser is
    # also round-trip-exact, so the value survives the text hop bit-for-bit.
    return " ".join(repr(float(x)) for x in np.asarray(xs).ravel())


def _fmt_ints(xs) -> str:
    return " ".join(str(int(x)) for x in np.asarray(xs).ravel())


def build_fixture_text(name: str) -> str:
    """Return the full text of the fixture for system ``name`` (no I/O)."""
    import tsdynamics as ts
    from tsdynamics.engine.rustcore import compile_tape

    spec = FIXTURE_SYSTEMS[name]
    system = getattr(ts, name)()
    dim = system.dim
    tape = compile_tape(system, with_jacobian=True)
    params = [float(system.params[k]) for k in tape.control_names]

    rhs = system._rhs_numeric()

    lines: list[str] = [_HEADER.rstrip("\n")]
    lines.append(f"system {name}")
    lines.append(f"n_state {tape.n_state}")
    lines.append(f"n_param {tape.n_param}")
    lines.append(f"dim {dim}")
    lines.append(f"ops {_fmt_ints(tape.ops)}")
    lines.append(f"a {_fmt_ints(tape.a)}")
    lines.append(f"b {_fmt_ints(tape.b)}")
    lines.append(f"imm {_fmt_floats(tape.imm)}")
    lines.append(f"outputs {_fmt_ints(tape.outputs)}")
    lines.append(f"jac_outputs {_fmt_ints(tape.jac_outputs)}".rstrip())
    lines.append(f"params {_fmt_floats(params)}".rstrip())

    for u, t in zip(spec["u"], spec["t"], strict=True):
        u = np.asarray(u, dtype=float)
        if u.size != dim:
            raise ValueError(f"{name}: checkpoint has {u.size} values, dim is {dim}")
        deriv = np.asarray(rhs(u, t), dtype=float).ravel()
        jac = np.asarray(system.jacobian(u, t), dtype=float).ravel()
        if not (np.all(np.isfinite(deriv)) and np.all(np.isfinite(jac))):
            raise ValueError(f"{name}: non-finite checkpoint at u={u}, t={t}")
        lines.append(f"cp_u {_fmt_floats(u)}")
        lines.append(f"cp_t {repr(float(t))}")
        lines.append(f"cp_deriv {_fmt_floats(deriv)}")
        lines.append(f"cp_jac {_fmt_floats(jac)}")

    return "\n".join(lines) + "\n"


def fixture_path(name: str) -> pathlib.Path:
    """Path of the committed fixture file for system ``name``."""
    return pathlib.Path(__file__).parent / "fixtures" / f"{name}.txt"


def parse_fixture(text: str) -> dict:
    """Parse a fixture back into a dict (the inverse of :func:`build_fixture_text`).

    Shared with ``tests/test_ir_contract.py`` so the Python drift guard reads the
    committed file with the exact same grammar the Rust test uses.
    """
    out: dict = {"checkpoints": []}
    int_keys = {"n_state", "n_param", "dim"}
    int_arrays = {"ops", "a", "b", "outputs", "jac_outputs"}
    float_arrays = {"imm", "params"}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, rest = line.partition(" ")
        rest = rest.strip()
        if key == "system":
            out[key] = rest
        elif key in int_keys:
            out[key] = int(rest)
        elif key in int_arrays:
            out[key] = [int(x) for x in rest.split()]
        elif key in float_arrays:
            out[key] = [float(x) for x in rest.split()]
        elif key == "cp_u":
            out["checkpoints"].append({"u": [float(x) for x in rest.split()]})
        elif key == "cp_t":
            out["checkpoints"][-1]["t"] = float(rest)
        elif key == "cp_deriv":
            out["checkpoints"][-1]["deriv"] = [float(x) for x in rest.split()]
        elif key == "cp_jac":
            out["checkpoints"][-1]["jac"] = [float(x) for x in rest.split()]
        else:
            raise ValueError(f"unknown fixture key {key!r}")
    return out


def main() -> None:
    """Write every fixture in :data:`FIXTURE_SYSTEMS` to ``fixtures/``."""
    out_dir = pathlib.Path(__file__).parent / "fixtures"
    out_dir.mkdir(exist_ok=True)
    for name in FIXTURE_SYSTEMS:
        text = build_fixture_text(name)
        fixture_path(name).write_text(text)
        print(f"wrote {fixture_path(name).relative_to(pathlib.Path.cwd())}")


if __name__ == "__main__":
    main()
