// Autogenerated by `scripts/gen_verner_ode_coeffs.py`.
// Source: SciML OrdinaryDiffEqVerner (`lib/OrdinaryDiffEqVerner/src/verner_tableaus.jl`), MIT license.
// Coefficients: J.H. Verner via OrdinaryDiffEq.jl.

pub(crate) const C10: f64 = 0.5;
pub(crate) const A1001: f64 = 0.016524159013572806;
pub(crate) const A1004: f64 = 0.3053128187514179;
pub(crate) const A1005: f64 = 0.2071200938201979;
pub(crate) const A1006: f64 = -1.293879140655123;
pub(crate) const A1007: f64 = 57.11988411588149;
pub(crate) const A1008: f64 = -55.87979207510932;
pub(crate) const A1009: f64 = 0.024830028297766014;
pub(crate) const C11: f64 = 0.828;
pub(crate) const A1101: f64 = 0.038150081818627744;
pub(crate) const A1104: f64 = 0.2502358252513705;
pub(crate) const A1105: f64 = 0.3249441447817608;
pub(crate) const A1106: f64 = 1.8224606658327962;
pub(crate) const A1107: f64 = -67.7137233269262;
pub(crate) const A1108: f64 = 66.03587911808127;
pub(crate) const A1109: f64 = -0.0363881087495127;
pub(crate) const A1110: f64 = 0.106441599909888;
pub(crate) const C12: f64 = 0.28;
pub(crate) const A1201: f64 = 0.11178168039666012;
pub(crate) const A1204: f64 = 0.025757505109345213;
pub(crate) const A1205: f64 = 3.785140856363646;
pub(crate) const A1206: f64 = 92.34088993695727;
pub(crate) const A1207: f64 = -3819.461508432344;
pub(crate) const A1208: f64 = 3732.492711530704;
pub(crate) const A1209: f64 = -1.0756940209963033;
pub(crate) const A1210: f64 = -3.231539970732086;
pub(crate) const A1211: f64 = -4.707539085458635;
