#!/usr/bin/env python3
"""Download OrdinaryDiffEq Verner CompiledFloat tableau chunks and emit Rust const files."""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

URL = (
    "https://raw.githubusercontent.com/SciML/OrdinaryDiffEq.jl/master/"
    "lib/OrdinaryDiffEqVerner/src/verner_tableaus.jl"
)

HEADER = """// Autogenerated by `scripts/gen_verner_ode_coeffs.py`.
// Source: SciML OrdinaryDiffEqVerner (`lib/OrdinaryDiffEqVerner/src/verner_tableaus.jl`), MIT license.
// Coefficients: J.H. Verner via OrdinaryDiffEq.jl.

"""


def rust_name(julia: str) -> str:
    head = "".join(c for c in julia if c.isalpha())
    tail = "".join(c for c in julia if c.isdigit())
    return f"{head.upper()}{tail}"


def emit_block(body: str) -> list[str]:
    rows: list[str] = []
    for m in re.finditer(
        r"^\s*(?P<jn>[a-z][a-z0-9_]*)\s*=\s*convert\((?:T|T2),\s*(?P<val>[^\)]*)\)",
        body,
        flags=re.MULTILINE,
    ):
        jn = m.group("jn")
        val = m.group("val").strip()
        if val.startswith(("big\"", "big'", "-big\"", "-big'", "BigInt")):
            continue
        if not re.match(r"^[0-9.eE+-]+$", val):
            continue
        if re.fullmatch(r"[+-]?\d+", val):
            val = f"{val}.0"
        rows.append(f"pub(crate) const {rust_name(jn)}: f64 = {val};")
    dedup = []
    seen: set[str] = set()
    for ln in rows:
        nm = ln.split()[2]
        if nm in seen:
            continue
        seen.add(nm)
        dedup.append(ln)
    return dedup


def slice_function(text: str, float_sig_needle: str, next_fn_needle: str) -> str:
    i = text.find(float_sig_needle)
    if i == -1:
        raise RuntimeError(f"needle not found: {float_sig_needle!r}")
    s = text.rfind("function ", 0, i)
    e = text.find(next_fn_needle, i)
    if e == -1:
        raise RuntimeError(f"next fn needle not found: {next_fn_needle!r}")
    return text[s:e]


def main() -> None:
    out_root = Path("crates/tsdyn-ode/src/methods")
    if not out_root.is_dir():
        print(f"Expect {out_root} to exist relative to cwd", file=sys.stderr)
        sys.exit(1)

    text = urllib.request.urlopen(URL, timeout=120).read().decode()

    # ---------- Vern6 ----------
    v6 = out_root / "vern6"
    v6.mkdir(exist_ok=True)
    tb6 = slice_function(
        text,
        "Vern6Tableau(T::Type{<:CompiledFloats}, T2::Type{<:CompiledFloats})",
        "function Vern6Tableau(::Type{T}, ::Type{T2}) where {T, T2}",
    )
    (v6 / "tableau_generated.rs").write_text(HEADER + "\n".join(emit_block(tb6)) + "\n", encoding="utf-8")

    ex6 = slice_function(
        text,
        "Vern6ExtraStages(T::Type{<:CompiledFloats}, T2::Type{<:CompiledFloats})",
        "function Vern6ExtraStages(::Type{T}, ::Type{T2}) where {T, T2}",
    )
    (v6 / "extra_generated.rs").write_text(
        HEADER + "\n".join(emit_block(ex6)) + "\n", encoding="utf-8"
    )

    i_s = text.find("function Vern6InterpolationCoefficients(T::Type{<:CompiledFloats}")
    i_e = text.find("function Vern6InterpolationCoefficients(::Type{T})", i_s + 10)
    (v6 / "interp_generated.rs").write_text(
        HEADER + "\n".join(emit_block(text[i_s:i_e])) + "\n",
        encoding="utf-8",
    )

    # ---------- Vern7 ----------
    v7 = out_root / "vern7"
    v7.mkdir(exist_ok=True)

    # CompiledFloat tableau is the `@fold Vern7Tableau` specialization (not rational BigInt tableau).
    u7 = ") where {T <: CompiledFloats, T2 <: CompiledFloats}\n    c2 = convert(T2, 0.005)"
    i7_c2 = text.find(u7)
    if i7_c2 == -1:
        raise RuntimeError("Vern7 CompiledFloat c2 anchor missing")
    s7_tb = text.rfind("@fold function Vern7Tableau(", 0, i7_c2)
    e7_tb = text.find(
        "@fold function Vern7Tableau(::Type{T}, ::Type{T2}) where {T, T2}", s7_tb
    )
    if s7_tb == -1 or e7_tb == -1 or e7_tb <= s7_tb:
        raise RuntimeError("Vern7 tableau slice malformed")
    tb7 = text[s7_tb:e7_tb]

    emitted7_tb = sorted(emit_block(tb7))
    (v7 / "tableau_generated.rs").write_text(HEADER + "\n".join(emitted7_tb) + "\n", encoding="utf-8")

    vsec = text.find("## Vern7")
    s7_full = text.find("@fold function Vern7ExtraStages(", vsec)
    if s7_full == -1:
        raise RuntimeError("Vern7 extra @fold start missing")
    e7_ex = text.find(
        "@fold function Vern7ExtraStages(::Type{T}, ::Type{T2}) where {T, T2}", s7_full + 20
    )
    if e7_ex == -1:
        raise RuntimeError("Vern7 extra rational @fold delimiter missing")
    ex7 = text[s7_full:e7_ex]
    (v7 / "extra_generated.rs").write_text(
        HEADER + "\n".join(emit_block(ex7)) + "\n", encoding="utf-8"
    )

    ip_s = text.find(
        "@fold function Vern7InterpolationCoefficients(::Type{T}) where {T <: CompiledFloats}"
    )
    ip_e = text.find("@fold function Vern7InterpolationCoefficients(::Type{T}) where {T}", ip_s + 80)
    (v7 / "interp_generated.rs").write_text(
        HEADER + "\n".join(sorted(emit_block(text[ip_s:ip_e]))) + "\n",
        encoding="utf-8",
    )

    # ---------- Vern8 ----------
    v8 = out_root / "vern8"
    v8.mkdir(exist_ok=True)

    tb8 = slice_function(
        text,
        "Vern8Tableau(T::Type{<:CompiledFloats}, T2::Type{<:CompiledFloats})",
        "function Vern8Tableau(::Type{T}, ::Type{T2}) where {T, T2}",
    )
    (v8 / "tableau_generated.rs").write_text(HEADER + "\n".join(emit_block(tb8)) + "\n", encoding="utf-8")

    ex8 = slice_function(
        text,
        "Vern8ExtraStages(T::Type{<:CompiledFloats}, T2::Type{<:CompiledFloats})",
        "function Vern8ExtraStages(::Type{T}, ::Type{T2}) where {T, T2}",
    )
    (v8 / "extra_generated.rs").write_text(
        HEADER + "\n".join(emit_block(ex8)) + "\n", encoding="utf-8"
    )

    ip_s8 = text.find("function Vern8InterpolationCoefficients(T::Type{<:CompiledFloats}")
    ip_e8 = text.find("function Vern8InterpolationCoefficients(::Type{T})", ip_s8 + 30)
    (v8 / "interp_generated.rs").write_text(
        HEADER + "\n".join(emit_block(text[ip_s8:ip_e8])) + "\n",
        encoding="utf-8",
    )

    print("OK: regenerated vern6/7/8 *_generated.rs under crates/tsdyn-ode/src/methods/")


if __name__ == "__main__":
    main()
