"""Version information for tsdynamics.

Resolves the installed package version via :mod:`importlib.metadata`. This
file is checked into git (it was auto-generated by hatch-vcs prior to R1).
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

__all__ = ["__version__", "version"]

try:
    __version__: str = _pkg_version("tsdynamics")
except PackageNotFoundError:  # pragma: no cover - only happens in uninstalled trees
    __version__ = "0.0.0+unknown"

version = __version__
